server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eduardomelle/config-server
          clone-on-start: true
          default-label: main
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 2000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
